name = "Downloader"
uuid = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
authors = ["Stefan Karpinski <stefan@karpinski.org> and contributors"]
version = "0.1.0"

[deps]
LibCURL = "b27032c2-a3e7-50c8-80cd-2d36dbcbfd21"

[compat]
LibCURL = "0.6"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
